

<select id="state_code" name="state_code">
   <option value=""></option>
   <option value="0">Not Specified</option>
   <option value="7">A.C.T</option>
   <option value="97">New South Wales</option>
   <option value="94">Northern Territory</option>
   <option value="107">Queensland</option>
   <option value="111">South Australia</option>
   <option value="140">Tasmania</option>
   <option value="144">Victoria</option>
   <option value="146">Western Australia</option>
   <option value="16">Barisal</option>
   <option value="20">Chittagong</option>
   <option value="30">Dhaka</option>
   <option value="71">Khulna</option>
   <option value="109">Rajshahi</option>
   <option value="153">Sylhet</option>
   <option value="46">Hong Kong</option>
   <option value="1">Aceh</option>
   <option value="9">Bali</option>
   <option value="10">Bangka Belitung</option>
   <option value="14">Banten</option>
   <option value="11">Bengkulu</option>
   <option value="37">Gorontalo</option>
   <option value="54" selected="selected">Jakarta Raya</option>
   <option value="55">Jambi</option>
   <option value="61">Jawa Barat</option>
   <option value="62">Jawa Tengah</option>
   <option value="64">Jawa Timur</option>
   <option value="67">Kalimantan Barat</option>
   <option value="72">Kalimantan Selatan</option>
   <option value="74">Kalimantan Tengah</option>
   <option value="75">Kalimantan Timur</option>
   <option value="310">Kalimantan Utara</option>
   <option value="233">Kepulauan Riau</option>
   <option value="79">Lampung</option>
   <option value="86">Maluku</option>
   <option value="84">Maluku Utara</option>
   <option value="90">Nusa Tenggara Barat</option>
   <option value="96">Nusa Tenggara Timur</option>
   <option value="52">Papua</option>
   <option value="234">Papua Barat</option>
   <option value="110">Riau</option>
   <option value="235">Sulawesi Barat</option>
   <option value="115">Sulawesi Selatan</option>
   <option value="116">Sulawesi Tengah</option>
   <option value="118">Sulawesi Tenggara</option>
   <option value="120">Sulawesi Utara</option>
   <option value="121">Sumatera Barat</option>
   <option value="124">Sumatera Selatan</option>
   <option value="125">Sumatera Utara</option>
   <option value="141">Timor Timur</option>
   <option value="152">Yogyakarta</option>
   <option value="3">Andaman &amp; Nicobar</option>
   <option value="4">Andhra Pradesh</option>
   <option value="8">Arunachal Pradesh</option>
   <option value="6">Assam</option>
   <option value="12">Bihar</option>
   <option value="19">Chandigarh</option>
   <option value="26">Chhattisgarh</option>
   <option value="31">Dadra &amp; Nagar Haveli</option>
   <option value="28">Daman &amp; Diu</option>
   <option value="29">Delhi</option>
   <option value="36">Goa</option>
   <option value="39">Gujarat</option>
   <option value="42">Haryana</option>
   <option value="49">Himachal Pradesh</option>
   <option value="57">Jammu &amp; Kashmir</option>
   <option value="59">Jharkhand</option>
   <option value="66">Karnataka</option>
   <option value="68">Kerala</option>
   <option value="76">Lakshadweep</option>
   <option value="88">Madhya Pradesh</option>
   <option value="80">Maharashtra</option>
   <option value="87">Manipur</option>
   <option value="82">Meghalaya</option>
   <option value="83">Mizoram</option>
   <option value="89">Nagaland</option>
   <option value="99">Orissa</option>
   <option value="103">Pondicherry</option>
   <option value="105">Punjab</option>
   <option value="108">Rajasthan</option>
   <option value="119">Sikkim</option>
   <option value="138">Tamil Nadu</option>
   <option value="139">Tripura</option>
   <option value="142">Uttar Pradesh</option>
   <option value="143">Uttaranchal</option>
   <option value="147">West Bengal</option>
   <option value="60">Japan</option>
   <option value="56">Johor</option>
   <option value="69">Kedah</option>
   <option value="73">Kelantan</option>
   <option value="70">Kuala Lumpur</option>
   <option value="77">Labuan</option>
   <option value="85">Melaka</option>
   <option value="95">Negeri Sembilan</option>
   <option value="101">Pahang</option>
   <option value="100">Penang</option>
   <option value="102">Perak</option>
   <option value="104">Perlis</option>
   <option value="232">Putrajaya</option>
   <option value="112">Sabah</option>
   <option value="127">Sarawak</option>
   <option value="122">Selangor</option>
   <option value="136">Terengganu</option>
   <option value="314">Testing. Please Do Not Select</option>
   <option value="5">Armm</option>
   <option value="15">Bicol Region</option>
   <option value="17">C.A.R</option>
   <option value="18">Cagayan Valley</option>
   <option value="126">Calabarzon &amp; Mimaropa</option>
   <option value="25">Caraga</option>
   <option value="21">Central Luzon</option>
   <option value="27">Central Visayas</option>
   <option value="123">Davao</option>
   <option value="32">Eastern Visayas</option>
   <option value="53">Ilocos Region</option>
   <option value="91">National Capital Reg</option>
   <option value="93">Northern Mindanao</option>
   <option value="22">Soccskargen</option>
   <option value="149">Western Visayas</option>
   <option value="148">Zamboanga</option>
   <option value="240">Central</option>
   <option value="238">East</option>
   <option value="236">North</option>
   <option value="237">North-East</option>
   <option value="117">Singapore</option>
   <option value="239">West</option>
   <option value="192">Ang Thong</option>
   <option value="193">Bangkok</option>
   <option value="174">Buri Ram</option>
   <option value="132">Central</option>
   <option value="194">Cha Choeng Sao</option>
   <option value="195">Chai Nat</option>
   <option value="175">Chaiyaphum</option>
   <option value="214">Chanthaburi</option>
   <option value="156">Chiang Mai</option>
   <option value="157">Chiang Rai</option>
   <option value="215">Chon Buri</option>
   <option value="218">Chumphon</option>
   <option value="133">Eastern</option>
   <option value="176">Kalasin</option>
   <option value="158">Kamphaeng Phet</option>
   <option value="196">Kanchanaburi</option>
   <option value="177">Khon Kaen</option>
   <option value="219">Krabi</option>
   <option value="159">Lampang</option>
   <option value="160">Lamphun</option>
   <option value="178">Loei</option>
   <option value="197">Lop Buri</option>
   <option value="161">Mae Hong Son</option>
   <option value="179">Maha Sarakham</option>
   <option value="180">Mukdahan</option>
   <option value="198">Nakhon Nayok</option>
   <option value="199">Nakhon Pathom</option>
   <option value="181">Nakhon Phanom</option>
   <option value="182">Nakhon Ratchasima</option>
   <option value="162">Nakhon Sawan</option>
   <option value="220">Nakhon Si Thammarat</option>
   <option value="163">Nan</option>
   <option value="221">Narathiwat</option>
   <option value="184">Nong Khai</option>
   <option value="183">Nongbua Lumphoo</option>
   <option value="200">Nonthaburi</option>
   <option value="130">North</option>
   <option value="131">North Eastern</option>
   <option value="201">Pathum Thani</option>
   <option value="222">Pattani</option>
   <option value="223">Phang Nga</option>
   <option value="224">Phatthalung</option>
   <option value="164">Phayao</option>
   <option value="165">Phetchabun</option>
   <option value="202">Phetchaburi</option>
   <option value="166">Phichit</option>
   <option value="167">Phitsanulok</option>
   <option value="203">Phra Nakhon Si Ayuttaya</option>
   <option value="168">Phrae</option>
   <option value="225">Phuket</option>
   <option value="204">Prachin Buri</option>
   <option value="205">Prachuap Khiri Khan</option>
   <option value="226">Ranong</option>
   <option value="206">Ratchaburi</option>
   <option value="216">Rayong</option>
   <option value="185">Roi Et</option>
   <option value="207">Sa kaew</option>
   <option value="186">Sakon Nakhon</option>
   <option value="208">Samut Prakan</option>
   <option value="209">Samut Sakhon</option>
   <option value="210">Samut Songkhram</option>
   <option value="211">Saraburi</option>
   <option value="227">Satun</option>
   <option value="187">Si Sa Ket</option>
   <option value="212">Sing Buri</option>
   <option value="228">Song Khla</option>
   <option value="134">South</option>
   <option value="169">Sukhothai</option>
   <option value="213">Suphan Buri</option>
   <option value="229">Surat Thani</option>
   <option value="188">Surin</option>
   <option value="170">Tak</option>
   <option value="230">Trang</option>
   <option value="217">Trat</option>
   <option value="189">Ubon Ratchathani</option>
   <option value="190">Udon Thani</option>
   <option value="173">Umnad Chareun</option>
   <option value="171">Uthai Thani</option>
   <option value="172">Uttaradit</option>
   <option value="231">Yala</option>
   <option value="191">Yasothon</option>
   <option value="241">An Giang</option>
   <option value="242">Ba Ria-Vung Tau</option>
   <option value="243">Bac Can</option>
   <option value="244">Bac Giang</option>
   <option value="245">Bac Lieu</option>
   <option value="246">Bac Ninh</option>
   <option value="247">Ben Tre</option>
   <option value="248">Binh Dinh</option>
   <option value="249">Binh Duong</option>
   <option value="250">Binh Phuoc</option>
   <option value="251">Binh Thuan</option>
   <option value="252">Ca Mau</option>
   <option value="253">Can Tho</option>
   <option value="254">Cao Bang</option>
   <option value="255">Da Nang</option>
   <option value="256">Dac Lac</option>
   <option value="309">Dak Nong</option>
   <option value="304">Dien Bien</option>
   <option value="257">Dong Nai</option>
   <option value="258">Dong Thap</option>
   <option value="259">Gia Lai</option>
   <option value="260">Ha Giang</option>
   <option value="261">Ha Nam</option>
   <option value="262">Ha Noi</option>
   <option value="263">Ha Tay</option>
   <option value="264">Ha Tinh</option>
   <option value="265">Hai Duong</option>
   <option value="266">Hai Phong</option>
   <option value="308">Hau Giang</option>
   <option value="267">Ho Chi Minh City</option>
   <option value="268">Hoa Binh</option>
   <option value="269">Hung Yen</option>
   <option value="270">Khanh Hoa</option>
   <option value="271">Kien Giang</option>
   <option value="272">Kon Tum</option>
   <option value="273">Lai Chau</option>
   <option value="274">Lam Dong</option>
   <option value="275">Lang Son</option>
   <option value="276">Lao Cai</option>
   <option value="277">Long An</option>
   <option value="307">Mekong Delta</option>
   <option value="278">Nam Dinh</option>
   <option value="279">Nghe An</option>
   <option value="280">Ninh Binh</option>
   <option value="281">Ninh Thuan</option>
   <option value="282">Phu Tho</option>
   <option value="283">Phu Yen</option>
   <option value="284">Quang Binh</option>
   <option value="285">Quang Nam</option>
   <option value="286">Quang Ngai</option>
   <option value="287">Quang Ninh</option>
   <option value="288">Quang Tri</option>
   <option value="289">Soc Trang</option>
   <option value="290">Son La</option>
   <option value="291">Tay Ninh</option>
   <option value="292">Thai Binh</option>
   <option value="293">Thai Nguyen</option>
   <option value="294">Thanh Hoa</option>
   <option value="295">Thua Thien-Hue</option>
   <option value="296">Tien Giang</option>
   <option value="297">Tra Vinh</option>
   <option value="298">Tuyen Quang</option>
   <option value="145">Vietnam</option>
   <option value="299">Vinh Long</option>
   <option value="300">Vinh Phuc</option>
   <option value="301">Yen Bai</option>
</select>

